### PR TITLE
fix!: adapt to changed HTML from distutils 0.17

### PR DESCRIPTION
**Pull request by nedbat**
The old distutils made sections like this:

    <div class="section">

As of 0.17, it makes them like this:

    <section>

With the new HTML and the old styling, our bullet lists had no bullets.

The bug report we wrote while looking into this:
https://sourceforge.net/p/docutils/bugs/417/

Jira: CENG-124

### CODE REVIEW

**Review by robrap — APPROVED** [review]
Thanks for the fix.

Note: we’ve got other styling bugs that have cropped up along the way and are not fixed. I think we should consider using an out-of-the box theme, or starting with one and documenting unique changes, so we can pull in updates to the base theme.

**Comment by nedbat** [comment]
Where are the other styling bugs listed?

**Comment by robrap** [comment]
> Where are the other styling bugs listed?

https://openedx.atlassian.net/wiki/x/MoFvn

**Comment by nedbat** [comment]
@robrap I am going to merge this fix to get some current projects looking right, and will also investigate moving off of our custom theme.

**Pull request merged**
